# Generated by Django 4.2.13 on 2024-07-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'INCOME'), (2, 'EXPENSE')], default=1),
        ),
    ]
